import { db } from "./db";
import { users, vehicles } from "@shared/schema";

async function seed() {
  console.log("🌱 Seeding database...");

  try {
    // Create sample users (owners)
    const [owner1, owner2] = await db.insert(users).values([
      {
        email: "owner1@driveease.com",
        password: "$2b$10$abcdefghijklmnopqrstuvwxyz123456", // hashed: password123
        firstName: "Rajesh",
        lastName: "Kumar",
        phone: "+91 9337 912331",
        role: "owner",
      },
      {
        email: "owner2@driveease.com",
        password: "$2b$10$abcdefghijklmnopqrstuvwxyz123456", // hashed: password123
        firstName: "Priya",
        lastName: "Sharma",
        phone: "+91 98765 43211",
        role: "owner",
      },
    ]).returning();

    console.log("✅ Created users");

    // Create sample vehicles - All in Bhubaneswar
    await db.insert(vehicles).values([
      // Cars
      {
        ownerId: owner1.id,
        name: "Honda City VX",
        type: "car",
        brand: "Honda",
        model: "City",
        year: 2023,
        seats: 5,
        fuelType: "petrol",
        transmission: "automatic",
        registrationNumber: "OD05AB1234",
        pricePerHour: "150",
        pricePerDay: "2500",
        location: "Patia, Bhubaneswar",
        ownerLocation: "Bhubaneswar",
        imageUrl: "https://images.unsplash.com/photo-1590362891991-f776e747a588?q=80&w=800",
        features: ["AC", "GPS", "Bluetooth", "Music System", "Power Steering"],
        hasExtraInsurance: true,
        extraInsuranceCost: "200",
        hasGpsTracking: true,
        available: true,
      },
      {
        ownerId: owner1.id,
        name: "Maruti Swift Dzire",
        type: "car",
        brand: "Maruti",
        model: "Swift Dzire",
        year: 2022,
        seats: 5,
        fuelType: "petrol",
        transmission: "manual",
        registrationNumber: "OD05CD5678",
        pricePerHour: "120",
        pricePerDay: "2000",
        location: "Chandrasekharpur, Bhubaneswar",
        ownerLocation: "Bhubaneswar",
        imageUrl: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?q=80&w=800",
        features: ["AC", "Bluetooth", "Power Windows", "Central Locking"],
        hasExtraInsurance: true,
        extraInsuranceCost: "150",
        available: true,
      },
      {
        ownerId: owner2.id,
        name: "Hyundai Creta SX",
        type: "car",
        brand: "Hyundai",
        model: "Creta",
        year: 2024,
        seats: 5,
        fuelType: "diesel",
        transmission: "automatic",
        registrationNumber: "OD05EF9012",
        pricePerHour: "200",
        pricePerDay: "3500",
        location: "Nayapalli, Bhubaneswar",
        ownerLocation: "Bhubaneswar",
        imageUrl: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=800",
        features: ["AC", "GPS", "Sunroof", "Bluetooth", "Cruise Control", "Touchscreen"],
        hasExtraInsurance: true,
        extraInsuranceCost: "250",
        hasGpsTracking: true,
        available: true,
      },
      {
        ownerId: owner2.id,
        name: "Toyota Innova Crysta",
        type: "car",
        brand: "Toyota",
        model: "Innova Crysta",
        year: 2023,
        seats: 7,
        fuelType: "diesel",
        transmission: "automatic",
        registrationNumber: "OD05GH3456",
        pricePerHour: "250",
        pricePerDay: "4000",
        location: "Saheed Nagar, Bhubaneswar",
        ownerLocation: "Bhubaneswar",
        imageUrl: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=800",
        features: ["AC", "GPS", "Bluetooth", "Touchscreen", "7 Seater", "Rear AC"],
        hasExtraInsurance: true,
        extraInsuranceCost: "300",
        hasGpsTracking: true,
        available: true,
      },
      {
        ownerId: owner1.id,
        name: "Tata Nexon XZ+",
        type: "car",
        brand: "Tata",
        model: "Nexon",
        year: 2024,
        seats: 5,
        fuelType: "electric",
        transmission: "automatic",
        registrationNumber: "OD05JK7890",
        pricePerHour: "180",
        pricePerDay: "3000",
        location: "Khandagiri, Bhubaneswar",
        ownerLocation: "Bhubaneswar",
        imageUrl: "https://images.unsplash.com/photo-1617654112368-307921291f42?q=80&w=800",
        features: ["AC", "GPS", "Bluetooth", "Touchscreen", "Electric", "Fast Charging"],
        hasExtraInsurance: true,
        extraInsuranceCost: "200",
        hasGpsTracking: true,
        available: true,
      },
      // Bikes
      {
        ownerId: owner1.id,
        name: "Royal Enfield Classic 350",
        type: "bike",
        brand: "Royal Enfield",
        model: "Classic 350",
        year: 2023,
        fuelType: "petrol",
        transmission: "manual",
        registrationNumber: "OD02IJ7890",
        pricePerHour: "80",
        pricePerDay: "1200",
        location: "Bapuji Nagar, Bhubaneswar",
        ownerLocation: "Bhubaneswar",
        imageUrl: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?q=80&w=800",
        features: ["Disc Brakes", "Electric Start", "Classic Design"],
        hasExtraInsurance: true,
        extraInsuranceCost: "100",
        available: true,
      },
      {
        ownerId: owner2.id,
        name: "Honda Activa 6G",
        type: "bike",
        brand: "Honda",
        model: "Activa 6G",
        year: 2024,
        fuelType: "petrol",
        transmission: "automatic",
        registrationNumber: "OD02KL1234",
        pricePerHour: "60",
        pricePerDay: "800",
        location: "Vani Vihar, Bhubaneswar",
        ownerLocation: "Bhubaneswar",
        imageUrl: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=800",
        features: ["Digital Display", "USB Charging", "LED Lights", "Comfortable Seat"],
        hasExtraInsurance: true,
        extraInsuranceCost: "80",
        available: true,
      },
      {
        ownerId: owner1.id,
        name: "Bajaj Pulsar NS200",
        type: "bike",
        brand: "Bajaj",
        model: "Pulsar NS200",
        year: 2023,
        fuelType: "petrol",
        transmission: "manual",
        registrationNumber: "OD02MN5678",
        pricePerHour: "70",
        pricePerDay: "1000",
        location: "Jaydev Vihar, Bhubaneswar",
        ownerLocation: "Bhubaneswar",
        imageUrl: "https://images.unsplash.com/photo-1609630875171-b1321377ee65?q=80&w=800",
        features: ["ABS", "Disc Brakes", "Digital Console", "LED Lights"],
        hasExtraInsurance: true,
        extraInsuranceCost: "90",
        available: true,
      },
      {
        ownerId: owner2.id,
        name: "TVS Apache RTR 160",
        type: "bike",
        brand: "TVS",
        model: "Apache RTR 160",
        year: 2022,
        fuelType: "petrol",
        transmission: "manual",
        registrationNumber: "OD02OP9012",
        pricePerHour: "65",
        pricePerDay: "900",
        location: "Rasulgarh, Bhubaneswar",
        ownerLocation: "Bhubaneswar",
        imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800",
        features: ["ABS", "LED Tail Lights", "Digital Speedometer", "Sporty Design"],
        hasExtraInsurance: true,
        extraInsuranceCost: "85",
        available: true,
      },
      {
        ownerId: owner2.id,
        name: "Hero Splendor Plus",
        type: "bike",
        brand: "Hero",
        model: "Splendor Plus",
        year: 2023,
        fuelType: "petrol",
        transmission: "manual",
        registrationNumber: "OD02QR3456",
        pricePerHour: "50",
        pricePerDay: "700",
        location: "Old Town, Bhubaneswar",
        ownerLocation: "Bhubaneswar",
        imageUrl: "https://images.unsplash.com/photo-1542282088-fe8426682b8f?q=80&w=800",
        features: ["Fuel Efficient", "Easy to Ride", "Comfortable", "Reliable"],
        hasExtraInsurance: true,
        extraInsuranceCost: "70",
        available: true,
      },
    ]);

    console.log("✅ Created vehicles");
    console.log("🎉 Database seeded successfully!");
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    throw error;
  }
}

seed()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
